[org]
name = "organisation"

[[org.tasks]]

[org.tasks.definition]
header = "définitions"
content = """
**organisation** (fractale) : groupe d'humains partageant une raison d'être commune (cercle racine) composé de roles et de cercles.  

**Role** : une fonction réalisé par une personne.  

**Circle** : ensemble de role et de sous-cercles (équipe, groupe etc).  

**Mandat** : document qui définit la fonction d'un role ou d'un cercle en explicitant :
* sa raison d'être : pourquoi il existe
* ses responsabilités (optionel) : quelle sont les attentes de ce role/cercle.
* ses domaines (optionel) : quelle propriétés/ressources il contrôle.
* ses politiques (optionel) : les regles d'acces à ses ressources.

**Tension** : distance entre la ou est là l'on veut aller. Une tension peut être utilisée par exemple pour partager et gérer des tâches, des questions ou des idées. Une tension, comme un courrier électronique, a un émetteur et un destinataire (un rôle ou un cercle).
Il y a trois grandes catégories de tension :
* Interne (ou de gouvernance) : concernant la structure de l'organisation, ses mandats etc.
* externe (ou opérationnelle) : concerne les actions mené par l'organisation.
* Entraide (ou Help) : pour les demandes d'aide, questions ou clarifications.
"""

[org.tasks.create]
header = "créer une organisation"
content = "Cliquez sur le bouton + dans le coin supérieur droit de la page. Cliquez ensuite sur le bouton 'Créer une nouvelle organisation'."

[org.tasks.mode]
header = "mode de l'organisation"
content = """
Le mode de l'organisation permet de définir la portée des droits associés au roles dans l'organisation. Il existe deux modes :

###### mode coordonné

Dans le mode coordoné, les rôles de coordinateur ont les droits suivant au sein de leurs cercles :
* création de rôles et de sous-cercles
* modification des rôles et des sous-cercles
* création de tensions et commentaires
* modification des tensions (titre, labels, assignés)
* déplacement des tensions

Les rôles normaux ont les droits suivante au sein de leurs cercles :
* création de tension et commentaires 
* fermer ses propres tensions 

###### mode agile

Dans le mode agile les rôles ont les droits suivant au sein de leurs cercles :
* création de rôles et de sous-cercles
* modification des rôles et des sous-cercles
* création de tension et commentaires
* modification de tension (titre, labels, assignés)
* déplacement des tensions

Note: les droits d'un rôle associé à un cercle sont hérité dans les sous-cercles qui ne possède pas rôles
"""


