site_name: Fractale documentation
site_url: https://doc.fractale.co/
repo_url: https://gitlab.com/fractale6/doc
repo_name: 'Source'

nav:
  - Introduction: index.md
  - Role & Circle: circle.md
  - Tension: tension.md
  - Quick Help: shorts/help.md

theme:
  name: material
  logo: assets/logo.png
  features:
    - toc.integrate
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

plugins:
  - search
  - i18n:
      default_language: en
      languages:
        en: English
        fr: Français
