site_name: Fractale documentation
site_url: https://doc.fractale.co/
repo_url: https://github.com/fractal6/doc
repo_name: 'Source' # works with repo_url
copyright: 'Copyright &copy; 2022 The Fractale Team'
extra_css:
  - stylesheets/extra.css


extra:
  #homepage: https://fractale.co
  generator: false
  social:
    - icon: custom/logo
      link: https://fractale.co
      name: fractale.co
    - icon: fontawesome/brands/github
      link: https://github.com/fractal6/doc
    - icon: material/chat-outline
      link: https://matrix.to/#/#fractal6:matrix.org
      name: Chat on matrix

nav:
  - Introduction: index.md
  - Role & Circle: circle.md
  - Tension: tension.md
  - Quick Help: _shorts/help.md
  - Developer FAQ: faq_dev.md

theme:
  name: material
  logo: assets/logo.png
  custom_dir: overrides
  features:
    - toc.integrate
    - announce.dismiss
  palette:
    - scheme: slate
      primary: teal
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: indigo
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

plugins:
  - search
  - i18n:
      default_language: en
      languages:
        en: English
        fr: Français

markdown_extensions:
  - tables
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - toc:
      baselevel: 1
